# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YU8H81XZZIAaWbEfutEeJar4V8a-7Vrs
"""

import streamlit as st
import torch
from transformers import AutoTokenizer, pipeline

# Load Model
model = "tiiuae/falcon-7b-instruct"
tokenizer = AutoTokenizer.from_pretrained(model)
device = "cuda" if torch.cuda.is_available() else "cpu"

pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.bfloat16,
    device_map=device,
    trust_remote_code=True
)

# Streamlit UI
st.title("🚀 Falcon-7B-Instruct Chatbot (Offline)")

user_input = st.text_area("Enter your prompt:")
if st.button("Generate Response"):
    with torch.no_grad():  # Faster inference
        response = pipeline(user_input, max_length=200, do_sample=True, top_k=10)
        st.write(response[0]['generated_text'])

